### ISSUE TITLE
form.populate doesn't seem to work.

### ISSUE THREAD

**Issue by jsivakumaran** [Voliware/Template#2]
I tried it at work with the form I was working on, then I made a simple form of only one input field and tried it on that.  

And now I'm at home and I used the example form in the example folder of this repository and it still isn't working.  It is entirely possible that I am not using it correctly. I would expect it to return a form with the input fields populated but instead it returns nothing (no form fields at all).

[Archive.zip](https://github.com/Voliware/Template/files/644648/Archive.zip)

It's the same three files as in the Template/examples/form except I do form.populate with a custom object I create.

**Comment by tones31** [comment]
Thanks Jay. I see/solved the problem.

I had extended jQuery with a function called 'populate', and gave Form a
function called 'populate'. Form's populate gets overwritten by jQuery when
Form inherits jQuery's function.

So now the function is called populateForm, which is really just a wrapper
for populateChildren, but sounds more appropriate.
